# Default Values:
# Border Color: Color::Rgb(79, 169, 210)
# Background Color: Color::Rgb(33, 33, 33)
# Highlight Color: Color::Rgb(79, 169, 210)
#
# Note: Only put RGB values
#

# Player Theme
Player Border Color: Color::Rgb(79, 169, 210)
Player Background Color: Color::Rgb(33, 33, 33)
Player Highlight Color: Color::Rgb(79, 169, 210)

# Library Theme
Library Border Color: Color::Rgb(79, 169, 210)
Library Background Color: Color::Rgb(33, 33, 33)
Library Highlight Color: Color::Rgb(79, 169, 210)

# Playlist Theme
Playlist Border Color: Color::Rgb(79, 169, 210)
Playlist Background Color: Color::Rgb(33, 33, 33)
Playlist Highlight Color: Color::Rgb(79, 169, 210)

# New Release Theme
New Release Border Color: Color::Rgb(79, 169, 210)
New Release Background Color: Color::Rgb(33, 33, 33)
New Release Highlight Color: Color::Rgb(79, 169, 210)

# Main Section Theme
Main Section Border Color: Color::Rgb(79, 169, 210)
Main Section Background Color: Color::Rgb(33, 33, 33)
Main Section Highlight Color: Color::Rgb(79, 169, 210)

# Search Theme
Search Border Color: Color::Rgb(79, 169, 210)
Search Background Color: Color::Rgb(33, 33, 33)
Search Highlight Color: Color::Rgb(79, 169, 210)

# Help Theme
Help Border Color: Color::Rgb(79, 169, 210)
Help Background Color: Color::Rgb(33, 33, 33)
Help Highlight Color: Color::Rgb(79, 169, 210)

# Error Screen Theme
Error Border Color: Color::Rgb(204, 0, 0)
Error Background Color: Color::Rgb(33, 33, 33)
